package kaist.iclab.mobiletracker.db.entity.watch

import io.objectbox.annotation.Entity
import io.objectbox.annotation.Id
import io.objectbox.annotation.Index
import kaist.iclab.mobiletracker.data.DeviceType
import kaist.iclab.mobiletracker.db.obx.EpochMillisIsoSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient

/**
 * ObjectBox entity for storing PPG (Photoplethysmography) sensor data received from watch.
 *
 * @property id Auto-generated primary key
 * @property eventId Unique event identifier generated by watch (UUID v4)
 * @property received Timestamp when phone received the data from watch (milliseconds)
 * @property timestamp Timestamp when watch recorded the data (milliseconds)
 * @property green Green light intensity value
 * @property greenStatus Status of the green light measurement
 * @property red Red light intensity value
 * @property redStatus Status of the red light measurement
 * @property ir Infrared light intensity value
 * @property irStatus Status of the infrared light measurement
 */
@Entity
@Serializable
data class WatchPPGEntity(
    @Id
    @Transient
    var id: Long = 0,
    @SerialName("event_id")
    var eventId: String = "",
    var uuid: String = "",
    @Serializable(with = EpochMillisIsoSerializer::class)
    var received: Long = 0,
    @Index
    @Serializable(with = EpochMillisIsoSerializer::class)
    var timestamp: Long = 0,
    var green: Int = 0,
    @SerialName("green_status")
    var greenStatus: Int = 0,
    var red: Int = 0,
    @SerialName("red_status")
    var redStatus: Int = 0,
    var ir: Int = 0,
    @SerialName("ir_status")
    var irStatus: Int = 0,
    @SerialName("device_type")
    var deviceType: Int = DeviceType.WATCH.value
)
