package kaist.iclab.mobiletracker.db.entity.watch

import io.objectbox.annotation.Entity
import io.objectbox.annotation.Id
import io.objectbox.annotation.Index

/**
 * Room entity for storing accelerometer sensor data received from watch.
 *
 * @property id Auto-generated primary key
 * @property eventId Unique event identifier generated by watch (UUID v4)
 * @property received Timestamp when phone received the data from watch (milliseconds)
 * @property timestamp Timestamp when watch recorded the data (milliseconds)
 * @property x Acceleration along x-axis (m/s²)
 * @property y Acceleration along y-axis (m/s²)
 * @property z Acceleration along z-axis (m/s²)
 */
@Entity
data class WatchAccelerometerEntity(
    @Id var id: Long = 0,
    var eventId: String = "",
    var uuid: String = "",
    var received: Long = 0,
    @Index var timestamp: Long = 0,
    var x: Float = 0f,
    var y: Float = 0f,
    var z: Float = 0f
)
