package kaist.iclab.mobiletracker.db.entity.watch

import io.objectbox.annotation.Entity
import io.objectbox.annotation.Id
import io.objectbox.annotation.Index

/**
 * Room entity for storing skin temperature sensor data received from watch.
 *
 * @property id Auto-generated primary key
 * @property eventId Unique event identifier generated by watch (UUID v4)
 * @property received Timestamp when phone received the data from watch (milliseconds)
 * @property timestamp Timestamp when watch recorded the data (milliseconds)
 * @property ambientTemp Ambient temperature in degrees Celsius
 * @property objectTemp Object (skin) temperature in degrees Celsius
 * @property status Status of the temperature measurement
 */
@Entity
data class WatchSkinTemperatureEntity(
    @Id var id: Long = 0,
    var eventId: String = "",
    var uuid: String = "",
    var received: Long = 0,
    @Index var timestamp: Long = 0,
    var ambientTemp: Float = 0f,
    var objectTemp: Float = 0f,
    var status: Int = 0
)
