#!/usr/bin/env python3
"""
generate_report.py — EnPULSE Benchmark Report Generator

This script automates the process of generating a beautiful benchmark report:
1. Pulls the latest benchmark CSV from the connected Android device via ADB.
2. Parses the metrics.csv.
3. Generates a publication-ready graph (PNG/PDF) showing Battery, CPU, and Memory.
4. Reads the summary.txt generated by the service and displays it in the terminal.

Requirements:
    pip install pandas matplotlib
"""

import argparse
import os
import subprocess
import sys

try:
    import pandas as pd
    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates
except ImportError:
    print("Error: Required libraries not found.")
    print("Please install them using: pip install pandas matplotlib")
    sys.exit(1)

def pull_latest_benchmark():
    """Uses ADB to find and pull the latest EnPULSE benchmark folder."""
    print("📱 Searching for latest benchmark folder on device...")
    try:
        # List all folders matching Benchmark_* in the EnPULSE directory, sorted by time (latest first)
        cmd = ["adb", "shell", "ls", "-td", "/sdcard/Download/EnPULSE/Benchmark_*"]
        output = subprocess.check_output(cmd, text=True, stderr=subprocess.DEVNULL)
        folders = [line.strip() for line in output.splitlines() if line.strip()]
        
        if not folders:
            print("❌ No benchmark folders found on the device.")
            return None
            
        latest_folder = folders[0]
        folder_name = os.path.basename(latest_folder)
        print(f"✅ Found latest folder: {folder_name}")
        
        # Create local output directory if it doesn't exist
        os.makedirs("outputs", exist_ok=True)
        local_path = os.path.join("outputs", folder_name)
        
        if not os.path.exists(local_path):
            print(f"📥 Pulling {folder_name} to {local_path}...")
            subprocess.check_call(["adb", "pull", latest_folder, local_path], stdout=subprocess.DEVNULL)
        else:
            print(f"ℹ️ Folder already exists locally at {local_path}. Using existing data.")
            
        return local_path
    except subprocess.CalledProcessError:
        print("❌ Failed to communicate with device. Is it connected and authorized via ADB?")
        return None

def generate_graph(folder_path):
    """Parses metrics.csv and generates a graph."""
    csv_path = os.path.join(folder_path, "metrics.csv")
    if not os.path.exists(csv_path):
        print(f"❌ Could not find metrics.csv in {folder_path}")
        return
        
    print(f"📊 Analyzing data from {csv_path}...")
    
    # Read CSV
    df = pd.read_csv(csv_path)
    if df.empty:
        print("❌ CSV is empty.")
        return
        
    # Parse timestamp
    df['timestamp'] = pd.to_datetime(df['timestamp_iso'])
    
    # Calculate elapsed time in minutes for x-axis
    start_time = df['timestamp'].iloc[0]
    df['elapsed_min'] = (df['timestamp'] - start_time).dt.total_seconds() / 60.0
    
    scenario_name = os.path.basename(folder_path).replace("Benchmark_", "")
    
    # Create the plot (3 subplots: Battery, CPU, Memory)
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(10, 10), sharex=True)
    
    # --- Plot 1: Battery Level & Charge ---
    ax1.plot(df['elapsed_min'], df['battery_level_pct'], color='red', linewidth=2, label='Battery Level (%)')
    ax1.set_ylabel('Battery Level (%)', color='red')
    ax1.tick_params(axis='y', labelcolor='red')
    ax1.set_title(f'EnPULSE Benchmark: {scenario_name}', fontsize=14, fontweight='bold')
    ax1.grid(True, linestyle='--', alpha=0.5)
    
    # Try plotting absolute charge on secondary y-axis if we have the charge counter
    if 'battery_charge_uah' in df.columns:
        # Convert uAh to mAh (or Wh if available, but mAh is standard)
        df['battery_charge_mah'] = df['battery_charge_uah'] / 1000.0
        # Check if we have valid non-negative/non-zero values
        if not (df['battery_charge_mah'] <= 0).all():
            ax1_twin = ax1.twinx()
            ax1_twin.plot(df['elapsed_min'], df['battery_charge_mah'], color='darkred', linestyle='--', alpha=0.7, label='Charge (mAh)')
            ax1_twin.set_ylabel('Remaining Charge (mAh)', color='darkred')
            ax1_twin.tick_params(axis='y', labelcolor='darkred')
            
            # Combine legends
            lines, labels = ax1.get_legend_handles_labels()
            lines2, labels2 = ax1_twin.get_legend_handles_labels()
            ax1.legend(lines + lines2, labels + labels2, loc='upper right')
        else:
            ax1.legend(loc='upper right')
    else:
        ax1.legend(loc='upper right')

    # Add start/end annotations for battery level
    start_bat = df['battery_level_pct'].iloc[0]
    end_bat = df['battery_level_pct'].iloc[-1]
    ax1.annotate(f'{start_bat}%', xy=(0, start_bat), xytext=(5, 5), 
                 textcoords='offset points', color='red', weight='bold')
    ax1.annotate(f'{end_bat}%', xy=(df['elapsed_min'].iloc[-1], end_bat), xytext=(-30, -15), 
                 textcoords='offset points', color='red', weight='bold')
    
    # --- Plot 2: CPU Usage & Temperature ---
    ax2.plot(df['elapsed_min'], df['cpu_usage_pct'], color='blue', linewidth=1.5, alpha=0.8, label='CPU Usage (%)')
    ax2.fill_between(df['elapsed_min'], df['cpu_usage_pct'], color='blue', alpha=0.1)
    ax2.set_ylabel('CPU Usage (%)', color='blue')
    ax2.tick_params(axis='y', labelcolor='blue')
    ax2.grid(True, linestyle='--', alpha=0.5)
    
    # Try plotting CPU temperature on secondary y-axis if we have it
    if 'cpu_temperature' in df.columns:
        valid_temps = df[df['cpu_temperature'] > 0]['cpu_temperature']
        if not valid_temps.empty:
            ax2_twin = ax2.twinx()
            ax2_twin.plot(df['elapsed_min'], df['cpu_temperature'], color='orange', linestyle='-', linewidth=1.2, label='CPU Temp (°C)')
            ax2_twin.set_ylabel('CPU Temperature (°C)', color='orange')
            ax2_twin.tick_params(axis='y', labelcolor='orange')
            
            # Combine legends
            lines, labels = ax2.get_legend_handles_labels()
            lines2, labels2 = ax2_twin.get_legend_handles_labels()
            ax2.legend(lines + lines2, labels + labels2, loc='upper right')
        else:
            ax2.legend(loc='upper right')
    else:
        ax2.legend(loc='upper right')
        
    # --- Plot 3: Memory Allocation ---
    ax3.plot(df['elapsed_min'], df['app_memory_mb'], color='green', linewidth=1.8, label='App Memory (PSS MB)')
    
    if 'native_heap_bytes' in df.columns:
        df['native_heap_mb'] = df['native_heap_bytes'] / (1024.0 * 1024.0)
        ax3.plot(df['elapsed_min'], df['native_heap_mb'], color='darkgreen', linestyle='--', linewidth=1.5, label='Native Heap (MB)')
        
    ax3.set_xlabel('Elapsed Time (minutes)')
    ax3.set_ylabel('Memory Usage (MB)')
    ax3.grid(True, linestyle='--', alpha=0.5)
    ax3.legend(loc='upper right')
    
    plt.tight_layout()
    
    # Save the plot
    output_image = os.path.join(folder_path, "benchmark_report.png")
    plt.savefig(output_image, dpi=300, bbox_inches='tight')
    print(f"🎉 Report Graph generated: {output_image}")
    
    # Save a PDF for the paper
    output_pdf = os.path.join(folder_path, "benchmark_report.pdf")
    plt.savefig(output_pdf, bbox_inches='tight')
    print(f"📄 High-res PDF generated: {output_pdf}")

def show_summary(folder_path):
    """Reads summary.txt and prints it in the terminal."""
    summary_path = os.path.join(folder_path, "summary.txt")
    if os.path.exists(summary_path):
        print("\n" + "=" * 50)
        print("📝 BENCHMARK SUMMARY REPORT")
        print("=" * 50)
        with open(summary_path, 'r') as f:
            print(f.read().strip())
        print("=" * 50 + "\n")

def main():
    parser = argparse.ArgumentParser(description="EnPULSE Benchmark Report Generator")
    parser.add_argument("--folder", help="Path to a local benchmark folder (bypasses ADB pull)")
    args = parser.parse_args()
    
    if args.folder:
        folder_path = args.folder
    else:
        folder_path = pull_latest_benchmark()
        
    if folder_path:
        generate_graph(folder_path)
        show_summary(folder_path)

if __name__ == "__main__":
    main()
